### ISSUE TITLE
rename template starter.json

### ISSUE THREAD

**Issue by dmtw** [colmena/template-api-extension#1]
Is there a way to rename the filenames like `template/common/models/starter.json` with the ModelName when generating with sao?
Have not found anything in the docs...

**Comment by beeman** [comment]
Hi @dmtw - Good question, this is definitely something that should be possible.

We might be able to use the `move` property for this https://github.com/egoist/sao/blob/0c2bdd939e0840b2892d359239e616de1c8a6f50/docs/create.md#move

**Comment by beeman** [comment]
I found a solution to rename files after scaffolding them:
```javascript
const path = require('path')
const {mv} = require('shelljs')

// A wrapper around mv that takes the base path as first argument
const fromTo = (folder, from, to) => mv(path.join(folder, from), path.join(folder, to))

// Takes the answers, runs them the the 'renames' method and runs the actual move
const renameFiles = (answers, folder) => renames(answers).forEach(({from, to}) => fromTo(from, from, to))

// Define here what files you want to have renamed after generation
const renames = (data) => ([
  {
    from: 'name.txt',
    to: `${data.moduleName}.txt`,
  },
  {
    from: 'sub/file.txt',
    to: `sub/${data.moduleName}.file.txt`,
  }
])


module.exports = {
  prompts: {
    moduleName: {
      message: 'What is the name of the new module (examples: Content/System/Storage...)?',
      default: 'MyName'
    },
  },
  post({answers, folderName}) {
    // Pluck 'answers' and 'folderName' from the result, pass it in the renameFiles method
    renameFiles(answers, folderName)
  },
}
```

**Comment by beeman** [comment]
Thanks to an update of SAO the files are now named correctly.

**Comment by dmtw** [comment]
I just tried this after npm i -g sao with no success. I still get the starter*.json files.

**Comment by dmtw** [comment]
had to use the template with --install flag. then the new template was pulled from git!
`sao --install colmena/template-api-extension test`
